global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "auth"
    static_configs:
      - targets: ["auth:3501"]

  - job_name: "profile"
    static_configs:
      - targets: ["profile:3502"]

  - job_name: "inventory"
    static_configs:
      - targets: ["inventory:3504"]

  - job_name: "product-order"
    static_configs:
      - targets: ["product-order:3505"]

  - job_name: "payments"
    static_configs:
      - targets: ["payments:3506"]

  - job_name: "shipping"
    static_configs:
      - targets: ["shipping:3507"]

  - job_name: "notifications"
    static_configs:
      - targets: ["notifications:3508"]

  - job_name: "images"
    static_configs:
      - targets: ["images:3509"]

  - job_name: "search"
    static_configs:
      - targets: ["search:3510"]

  - job_name: "gateway"
    static_configs:
      - targets: ["gateway:3500"]
